// ═══════════════════════════════════════════════════════════
//  DespatchFlow — Main JS
//
//  MOCK_MODE = true  → works without a backend (fake data)
//  MOCK_MODE = false → talks to real FastAPI backend
//
//  AUTH FLOW (real backend):
//    POST /ubl/auth/register  {username, password} → {message}
//    POST /ubl/auth/login     {username, password} → {access_token, token_type}
//    All despatch endpoints → needs: Authorization: Bearer <token>
// ═══════════════════════════════════════════════════════════

const MOCK_MODE = false;
// Use 'http://localhost:8000' when running backend locally with python run.py
// Use the AWS URL below when the deployment is fixed
// const API_BASE = 'https://rhumzuhvabxxwsemnufzash5ue0wubck.lambda-url.ap-southeast-2.on.aws';
const API_BASE  = 'http://localhost:8000';

// ─── Token management ────────────────────────────────────────
const getToken    = ()  => localStorage.getItem('df_token');
const getUsername = ()  => localStorage.getItem('df_username');
const saveSession = (token, username) => {
    localStorage.setItem('df_token', token);
    localStorage.setItem('df_username', username);
};
const clearSession = () => {
    localStorage.removeItem('df_token');
    localStorage.removeItem('df_username');
};

// ─── API helpers ─────────────────────────────────────────────

// JSON call — used for auth endpoints (register, login, logout)
const apiCall = async (path, method = 'GET', body = null) => {
    const headers = { 'Content-Type': 'application/json' };
    if (getToken()) headers['Authorization'] = `Bearer ${getToken()}`;

    const opts = { method, headers };
    if (body) opts.body = JSON.stringify(body);

    const res = await fetch(`${API_BASE}/${path}`, opts);
    const data = await res.json().catch(() => ({}));

    if (!res.ok) throw new Error(data.detail || `Error ${res.status}`);
    return data;
};

// Multipart/form-data call — used for file uploads (generate)
// Do NOT set Content-Type manually; browser sets it with the boundary
const formCall = async (path, formData) => {
    const res = await fetch(`${API_BASE}/${path}`, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${getToken()}` },
        body: formData
    });

    if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        // 401 means token expired or missing
        if (res.status === 401) {
            clearSession();
            updateAuthUI();
            showToast('Session expired — please log in again', 'error');
        }
        throw new Error(err.detail || `Error ${res.status}`);
    }
    return res; // caller handles blob download
};

// Authenticated JSON GET — used for list, delete etc.
const authCall = async (path, method = 'GET') => {
    if (!getToken()) throw new Error('Not logged in');
    const res = await fetch(`${API_BASE}/${path}`, {
        method,
        headers: { 'Authorization': `Bearer ${getToken()}` }
    });
    const data = await res.json().catch(() => ({}));

    if (res.status === 401) {
        clearSession();
        updateAuthUI();
        showToast('Session expired — please log in again', 'error');
    }
    if (!res.ok) throw new Error(data.detail || `Error ${res.status}`);
    return data;
};

// ─── Mock data (used when MOCK_MODE = true) ──────────────────
const mockStore = {
    token: null, username: null,
    documents: [
        { uuid: 'b0e63b53-f9bd-49fa-8983-f30c178b3e95', despatch_id: 'ORD-001', created_at: '2026-04-10T10:00:00' },
        { uuid: 'c1f74c64-a0ce-4a3d-9174-003c178b4ea6', despatch_id: 'ORD-002', created_at: '2026-04-12T14:30:00' },
        { uuid: 'd2a85d75-b1df-4b4e-a285-114d289c5fb7', despatch_id: 'ORD-003', created_at: '2026-04-14T09:15:00' },
        { uuid: 'e3b96e86-c2e0-5c5f-b396-225e39ad60c8', despatch_id: 'ORD-004', created_at: '2026-04-16T11:45:00' },
    ],
};
const mockDelay = (ms = 700) => new Promise(r => setTimeout(r, ms));
const MOCK_XML = (orderId, carrier, date, notes) =>
`<?xml version="1.0" encoding="UTF-8"?>
<DespatchAdvice
  xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"
  xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
  xmlns="urn:oasis:names:specification:ubl:schema:xsd:DespatchAdvice-2">
  <cbc:UBLVersionID>2.1</cbc:UBLVersionID>
  <cbc:ID>${orderId}</cbc:ID>
  <cbc:IssueDate>${date || new Date().toISOString().split('T')[0]}</cbc:IssueDate>
  <cbc:DespatchAdviceTypeCode>delivery</cbc:DespatchAdviceTypeCode>
  <cbc:Note>${notes || 'Generated by DespatchFlow'}</cbc:Note>
  <!-- Carrier: ${carrier || 'Not specified'} -->
</DespatchAdvice>`;

// ═══════════════════════════════════════════════════════════
//  Navigation
// ═══════════════════════════════════════════════════════════
const pages = {
    dashboard: 'Dashboard',
    generate:  'Generate Despatch',
    documents: 'My Documents',
    validate:  'Validate XML',
};

const navigateTo = (pageId) => {
    if (!pages[pageId]) return;
    document.querySelectorAll('.page').forEach(p => p.classList.remove('active'));
    document.querySelectorAll('.nav-item').forEach(n => n.classList.remove('active'));
    document.getElementById(`page-${pageId}`).classList.add('active');
    document.querySelector(`.nav-item[data-page="${pageId}"]`)?.classList.add('active');
    document.getElementById('page-heading').textContent = pages[pageId];
    if (pageId === 'documents') loadDocuments();
    if (pageId === 'dashboard')  loadDashboard();
};

document.addEventListener('click', (e) => {
    const el = e.target.closest('[data-page]');
    if (el) { e.preventDefault(); navigateTo(el.dataset.page); }
});

// ═══════════════════════════════════════════════════════════
//  Auth UI
// ═══════════════════════════════════════════════════════════
const updateAuthUI = () => {
    const loggedIn = MOCK_MODE ? !!mockStore.token : !!getToken();
    const username = MOCK_MODE ? mockStore.username : getUsername();

    document.getElementById('auth-buttons').style.display  = loggedIn ? 'none' : 'flex';
    document.getElementById('logout-btn').style.display    = loggedIn ? 'flex' : 'none';
    document.getElementById('user-avatar').textContent     = loggedIn ? (username?.[0]?.toUpperCase() || 'U') : '?';
    document.getElementById('user-name-display').textContent = loggedIn ? username : 'Guest';
    document.getElementById('mock-badge').style.display    = MOCK_MODE ? 'flex' : 'none';
};

// ─── Modal helpers ───────────────────────────────────────────
const openModal = (id) => {
    document.getElementById('modal-overlay').style.display = 'flex';
    document.getElementById('login-modal').style.display    = id === 'login-modal'    ? 'block' : 'none';
    document.getElementById('register-modal').style.display = id === 'register-modal' ? 'block' : 'none';
};
const closeModal = () => {
    document.getElementById('modal-overlay').style.display = 'none';
    document.getElementById('login-error').textContent    = '';
    document.getElementById('register-error').textContent = '';
};

document.getElementById('login-nav-btn').addEventListener('click',    () => openModal('login-modal'));
document.getElementById('register-nav-btn').addEventListener('click', () => openModal('register-modal'));
document.querySelectorAll('[data-close-modal]').forEach(b => b.addEventListener('click', closeModal));
document.getElementById('modal-overlay').addEventListener('click', (e) => { if (e.target === e.currentTarget) closeModal(); });
document.getElementById('switch-to-register').addEventListener('click', (e) => { e.preventDefault(); openModal('register-modal'); });
document.getElementById('switch-to-login').addEventListener('click',    (e) => { e.preventDefault(); openModal('login-modal'); });

// ─── Login ───────────────────────────────────────────────────
// Flow: POST /ubl/auth/login with JSON → get access_token → save it
document.getElementById('login-form').addEventListener('submit', async (e) => {
    e.preventDefault();
    const errEl    = document.getElementById('login-error');
    const username = document.getElementById('login-username').value.trim();
    const password = document.getElementById('login-password').value;
    errEl.textContent = '';

    if (!username || !password) { errEl.textContent = 'Both fields are required'; return; }

    setLoading('login-form', true);
    try {
        if (MOCK_MODE) {
            await mockDelay();
            mockStore.token = 'mock_token'; mockStore.username = username;
        } else {
            // POST JSON — returns { access_token, token_type }
            const res = await apiCall('ubl/auth/login', 'POST', { username, password });
            saveSession(res.access_token, username);
        }
        closeModal();
        updateAuthUI();
        showToast(`Welcome back, ${username}!`, 'success');
        loadDashboard();
    } catch (err) {
        errEl.textContent = err.message;
    } finally {
        setLoading('login-form', false);
    }
});

// ─── Register ────────────────────────────────────────────────
// Flow: POST /ubl/auth/register → {message} (no token)
//       then POST /ubl/auth/login to get the token
document.getElementById('register-form').addEventListener('submit', async (e) => {
    e.preventDefault();
    const errEl    = document.getElementById('register-error');
    const username = document.getElementById('reg-username').value.trim();
    const password = document.getElementById('reg-password').value;
    const confirm  = document.getElementById('reg-confirm').value;
    errEl.textContent = '';

    if (!username || !password)     { errEl.textContent = 'All fields are required'; return; }
    if (password !== confirm)        { errEl.textContent = 'Passwords do not match'; return; }
    if (password.length < 4)         { errEl.textContent = 'Password must be at least 4 characters'; return; }

    setLoading('register-form', true);
    try {
        if (MOCK_MODE) {
            await mockDelay(500);
            mockStore.token = 'mock_token'; mockStore.username = username;
        } else {
            // Step 1: register (returns {message}, NOT a token)
            await apiCall('ubl/auth/register', 'POST', { username, password });
            // Step 2: login to get the token
            const res = await apiCall('ubl/auth/login', 'POST', { username, password });
            saveSession(res.access_token, username);
        }
        closeModal();
        updateAuthUI();
        showToast(`Account created! Welcome, ${username}`, 'success');
        loadDashboard();
    } catch (err) {
        errEl.textContent = err.message;
    } finally {
        setLoading('register-form', false);
    }
});

// ─── Logout ──────────────────────────────────────────────────
// Backend logout is stateless (just returns {message}), so we only need to clear local token
document.getElementById('logout-btn').addEventListener('click', async () => {
    if (!MOCK_MODE) {
        try { await apiCall('ubl/auth/logout', 'POST'); } catch(_) { /* ignore */ }
    }
    MOCK_MODE ? (mockStore.token = null, mockStore.username = null) : clearSession();
    updateAuthUI();
    showToast('Logged out');
    navigateTo('dashboard');
});

// ═══════════════════════════════════════════════════════════
//  Dashboard
// ═══════════════════════════════════════════════════════════
const loadDashboard = async () => {
    if (!(MOCK_MODE ? mockStore.token : getToken())) {
        // Not logged in — show empty state
        document.getElementById('recent-doc-list').innerHTML =
            '<p style="color:var(--text-3);font-size:13px;padding:8px 0">Log in to see your documents.</p>';
        document.getElementById('stat-total').textContent = '—';
        document.getElementById('stat-recent').textContent = '—';
        return;
    }

    try {
        const docs = MOCK_MODE ? await mockDelay(300).then(() => mockStore.documents) 
                               : await authCall('ubl/v3/despatch-advice/list');

        document.getElementById('stat-total').textContent = docs.length;
        // "this week" = docs created in last 7 days
        const weekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
        const recent  = docs.filter(d => d.created_at && new Date(d.created_at) > weekAgo);
        document.getElementById('stat-recent').textContent = recent.length;

        const list = document.getElementById('recent-doc-list');
        if (!docs.length) {
            list.innerHTML = '<p style="color:var(--text-3);font-size:13px;padding:8px 0">No documents yet.</p>';
            return;
        }
        list.innerHTML = docs.slice(0, 5).map(d => `
            <div class="doc-row">
                <div class="doc-row-left">
                    <div class="doc-row-icon">
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                            <polyline points="14 2 14 8 20 8"/>
                        </svg>
                    </div>
                    <div>
                        <div class="doc-row-id">${d.despatch_id}</div>
                        <div class="doc-row-uuid">${d.uuid}</div>
                    </div>
                </div>
                <div class="doc-row-date">${formatDate(d.created_at)}</div>
            </div>`).join('');
    } catch (err) {
        document.getElementById('recent-doc-list').innerHTML =
            `<p style="color:var(--red);font-size:13px">${err.message}</p>`;
    }
};

// ═══════════════════════════════════════════════════════════
//  Generate Despatch
// ═══════════════════════════════════════════════════════════
let selectedFile     = null;
let generatedXmlData = null;

setupDropZone(
    'drop-zone', 'drop-zone-inner', 'drop-zone-file',
    'file-name-display', 'remove-file', 'xml-file-input',
    'browse-link',
    (f) => { selectedFile = f; }
);

document.getElementById('generate-form').addEventListener('submit', async (e) => {
    e.preventDefault();

    if (!selectedFile) { showToast('Please upload an Order XML file', 'error'); return; }

    if (!(MOCK_MODE ? mockStore.token : getToken())) {
        showToast('You must be logged in to generate a despatch', 'error');
        openModal('login-modal');
        return;
    }

    const carrier = document.getElementById('carrier-input').value;
    const date    = document.getElementById('date-input').value;
    const notes   = document.getElementById('notes-input').value;
    const btn     = document.getElementById('generate-submit-btn');

    btn.disabled = true;
    btn.innerHTML = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="animation:spin 1s linear infinite"><path d="M21 12a9 9 0 1 1-6.22-8.56"/></svg> Generating…';

    try {
        let xml, uuid, filename;

        if (MOCK_MODE) {
            await mockDelay(900);
            const orderId = 'ORD-' + String(mockStore.documents.length + 1).padStart(3, '0');
            uuid     = crypto.randomUUID();
            xml      = MOCK_XML(orderId, carrier, date, notes);
            filename = `Despatch_${orderId}_${uuid}.xml`;
            mockStore.documents.unshift({ uuid, despatch_id: orderId, created_at: new Date().toISOString() });
        } else {
            // Backend expects multipart/form-data with:
            //   order_xml (file), carrier (str), dispatch_date (str), notes (str)
            // And Authorization: Bearer <token> in the header
            const fd = new FormData();
            fd.append('order_xml', selectedFile);         // ← key must be "order_xml"
            fd.append('carrier', carrier);
            fd.append('dispatch_date', date);
            fd.append('notes', notes);

            const res = await formCall('ubl/v3/despatch-advice/generate', fd);

            // Response is a streaming XML file download
            // UUID is in the response header "Despatch-UUID"
            uuid     = res.headers.get('Despatch-UUID') || '';
            const cd = res.headers.get('Content-Disposition') || '';
            filename = cd.match(/filename="(.+)"/)?.[1] || 'despatch.xml';
            const blob = await res.blob();
            xml = await blob.text();
            generatedXmlData = { blob, filename };
        }

        // Show preview
        document.getElementById('preview-empty').style.display  = 'none';
        document.getElementById('preview-result').style.display = 'block';
        document.getElementById('preview-filename').textContent = filename;
        document.getElementById('preview-uuid').textContent     = uuid;
        document.getElementById('xml-preview-content').textContent = xml.trim();
        if (MOCK_MODE) generatedXmlData = { xml, filename };

        showToast('Despatch Advice generated!', 'success');
        loadDashboard();
    } catch (err) {
        showToast(err.message, 'error');
    } finally {
        btn.disabled = false;
        btn.innerHTML = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg> Generate Despatch Advice';
    }
});

document.getElementById('download-btn').addEventListener('click', () => {
    if (!generatedXmlData) return;
    const blob = generatedXmlData.blob
        || new Blob([generatedXmlData.xml], { type: 'application/xml' });
    const url = URL.createObjectURL(blob);
    Object.assign(document.createElement('a'), { href: url, download: generatedXmlData.filename }).click();
    URL.revokeObjectURL(url);
    showToast('Downloaded!', 'success');
});

// ═══════════════════════════════════════════════════════════
//  Documents
// ═══════════════════════════════════════════════════════════
const loadDocuments = async () => {
    const tbody = document.getElementById('doc-table-body');
    const empty = document.getElementById('table-empty');
    empty.style.display = 'none';

    if (!(MOCK_MODE ? mockStore.token : getToken())) {
        tbody.innerHTML = `<tr><td colspan="4" style="color:var(--text-3);text-align:center;padding:24px">
            Log in to view your documents.</td></tr>`;
        return;
    }

    tbody.innerHTML = `<tr><td colspan="4" style="color:var(--text-3);text-align:center;padding:24px">Loading…</td></tr>`;

    try {
        // GET /ubl/v3/despatch-advice/list  → [{uuid, despatch_id}, ...]
        // Note: list endpoint returns uuid + despatch_id only (no created_at)
        const docs = MOCK_MODE
            ? await mockDelay(300).then(() => [...mockStore.documents])
            : await authCall('ubl/v3/despatch-advice/list');

        let filtered = [...docs];

        const renderTable = () => {
            if (!filtered.length) {
                tbody.innerHTML = '';
                empty.style.display = 'block';
                return;
            }
            tbody.innerHTML = filtered.map(d => `
                <tr>
                    <td><span class="mono">${d.despatch_id}</span></td>
                    <td><span class="mono small">${d.uuid}</span></td>
                    <td style="color:var(--text-2)">${formatDate(d.created_at)}</td>
                    <td>
                        <div class="action-btns">
                            <button class="action-btn" onclick="downloadDoc('${d.uuid}','${d.despatch_id}')">Download</button>
                            <button class="action-btn danger" onclick="deleteDoc('${d.despatch_id}','${d.uuid}')">Delete</button>
                        </div>
                    </td>
                </tr>`).join('');
        };

        renderTable();

        // Live search
        document.getElementById('doc-search').oninput = (e) => {
            const q = e.target.value.toLowerCase();
            filtered = docs.filter(d =>
                d.despatch_id.toLowerCase().includes(q) ||
                d.uuid.toLowerCase().includes(q)
            );
            renderTable();
        };
    } catch (err) {
        tbody.innerHTML = `<tr><td colspan="4" style="color:var(--red);text-align:center;padding:24px">${err.message}</td></tr>`;
    }
};

// Download: GET /ubl/v3/despatch-advice/uuid/download/{uuid}  (needs Bearer token)
window.downloadDoc = async (uuid, id) => {
    if (MOCK_MODE) {
        const xml  = MOCK_XML(id, '', '', '');
        const blob = new Blob([xml], { type: 'application/xml' });
        const url  = URL.createObjectURL(blob);
        Object.assign(document.createElement('a'), { href: url, download: `Despatch_${id}.xml` }).click();
        URL.revokeObjectURL(url);
        showToast('Downloaded ' + id, 'success');
        return;
    }
    // Fetch with auth header so the protected endpoint accepts it
    try {
        const res = await fetch(`${API_BASE}/ubl/v3/despatch-advice/uuid/download/${uuid}`, {
            headers: { 'Authorization': `Bearer ${getToken()}` }
        });
        if (!res.ok) throw new Error(`Error ${res.status}`);
        const blob = await res.blob();
        const url  = URL.createObjectURL(blob);
        Object.assign(document.createElement('a'), { href: url, download: `Despatch_${id}.xml` }).click();
        URL.revokeObjectURL(url);
        showToast('Downloaded ' + id, 'success');
    } catch (err) {
        showToast(err.message, 'error');
    }
};

// Delete: DELETE /ubl/v3/despatch-advice/id/{id}  (needs Bearer token)
window.deleteDoc = async (id, uuid) => {
    if (!confirm(`Delete despatch "${id}"?`)) return;
    if (MOCK_MODE) {
        const i = mockStore.documents.findIndex(d => d.uuid === uuid);
        if (i > -1) mockStore.documents.splice(i, 1);
    } else {
        try {
            await authCall(`ubl/v3/despatch-advice/id/${id}`, 'DELETE');
        } catch (err) {
            showToast(err.message, 'error');
            return;
        }
    }
    showToast('Deleted ' + id, 'success');
    loadDocuments();
    loadDashboard();
};

// ═══════════════════════════════════════════════════════════
//  Validate
// ═══════════════════════════════════════════════════════════
let validateFile = null;

setupDropZone(
    'validate-drop-zone', 'validate-drop-inner', 'validate-file-display',
    'validate-filename', 'validate-remove', 'validate-file-input',
    'validate-browse',
    (f) => { validateFile = f; }
);

document.getElementById('validate-btn').addEventListener('click', async () => {
    if (!validateFile) { showToast('Please upload an XML file first', 'error'); return; }

    const btn = document.getElementById('validate-btn');
    btn.disabled = true; btn.textContent = 'Validating…';

    try {
        let valid, errors;
        if (MOCK_MODE) {
            await mockDelay(800);
            const text = await validateFile.text();
            valid  = text.trim().startsWith('<?xml') || text.trim().startsWith('<');
            errors = valid ? [] : ['File does not appear to be valid XML'];
        } else {
            // POST multipart to /ubl/v2/despatch-advice/validate
            const fd = new FormData();
            fd.append('file', validateFile);
            const res = await fetch(`${API_BASE}/ubl/v2/despatch-advice/validate`, {
                method: 'POST',
                headers: { 'Authorization': `Bearer ${getToken()}` },
                body: fd
            });
            const data = await res.json().catch(() => ({}));
            if (!res.ok) throw new Error(data.detail || `Error ${res.status}`);
            valid  = data.valid ?? (res.ok);
            errors = data.errors || [];
        }

        document.getElementById('validate-empty').style.display          = 'none';
        document.getElementById('validate-result-content').style.display = 'block';
        document.getElementById('validate-status').innerHTML = valid
            ? '<div class="meta-badge success">✓ Valid UBL 2.1 Document</div>'
            : '<div class="meta-badge error">✗ Validation Failed</div>';
        document.getElementById('validate-details').textContent = valid
            ? 'No schema violations found. The document conforms to the UBL 2.1 XSD specification.'
            : (errors.join('\n') || 'Unknown validation error.');

        showToast(valid ? 'Document is valid!' : 'Validation failed', valid ? 'success' : 'error');
    } catch (err) {
        showToast(err.message, 'error');
    } finally {
        btn.disabled = false;
        btn.innerHTML = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 12l2 2 4-4"/><path d="M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z"/></svg> Run Validation';
    }
});

// ═══════════════════════════════════════════════════════════
//  Shared: Drop Zone Setup
// ═══════════════════════════════════════════════════════════
function setupDropZone(zoneId, innerId, fileDisplayId, fileNameId, removeId, inputId, browseLinkId, onFile) {
    const zone        = document.getElementById(zoneId);
    const inner       = document.getElementById(innerId);
    const fileDisplay = document.getElementById(fileDisplayId);
    const fileNameEl  = document.getElementById(fileNameId);
    const removeBtn   = document.getElementById(removeId);
    const input       = document.getElementById(inputId);
    const browseLink  = document.getElementById(browseLinkId);

    const showFile = (file) => {
        inner.style.display       = 'none';
        fileDisplay.style.display = 'flex';
        fileNameEl.textContent    = file.name;
        onFile(file);
    };
    const clearFile = () => {
        inner.style.display       = '';
        fileDisplay.style.display = 'none';
        input.value               = '';
        onFile(null);
    };

    zone.addEventListener('click', (e) => {
        if (fileDisplay.style.display !== 'flex') input.click();
    });
    browseLink?.addEventListener('click', (e) => { e.stopPropagation(); input.click(); });
    input.addEventListener('change', () => { if (input.files[0]) showFile(input.files[0]); });
    removeBtn.addEventListener('click', (e) => { e.stopPropagation(); clearFile(); });
    zone.addEventListener('dragover',  (e) => { e.preventDefault(); zone.classList.add('dragging'); });
    zone.addEventListener('dragleave', ()  => zone.classList.remove('dragging'));
    zone.addEventListener('drop', (e) => {
        e.preventDefault(); zone.classList.remove('dragging');
        const f = e.dataTransfer.files[0];
        if (f?.name.endsWith('.xml')) showFile(f);
        else showToast('Please drop a .xml file', 'error');
    });
}

// ═══════════════════════════════════════════════════════════
//  Utilities
// ═══════════════════════════════════════════════════════════
const formatDate = (iso) => {
    if (!iso) return '—';
    try { return new Date(iso).toLocaleDateString('en-AU', { day: 'numeric', month: 'short', year: 'numeric' }); }
    catch { return iso; }
};

let toastTimer;
const showToast = (msg, type = '') => {
    const t = document.getElementById('toast');
    t.textContent = msg;
    t.className   = `toast show ${type}`;
    clearTimeout(toastTimer);
    toastTimer = setTimeout(() => { t.className = 'toast'; }, 3200);
};

const setLoading = (formId, loading) => {
    const btn = document.querySelector(`#${formId} button[type="submit"]`);
    if (!btn) return;
    btn.disabled = loading;
    if (loading) { btn.dataset.orig = btn.innerHTML; btn.textContent = 'Loading…'; }
    else btn.innerHTML = btn.dataset.orig || btn.innerHTML;
};

// ─── Init ─────────────────────────────────────────────────────
updateAuthUI();
loadDashboard();
